algoritmo "semnome"
// Função :
// Autor :
// Data : 13/04/2021
// Seção de Declarações 
var
min, hora, resultado: real
inicio

escreval("esse algoritimo realiza a conversão de minutos em hora")

// Seção de Comandos

escreval("insira a quantidade de minutos")
leia (min)

escreval("a quantidade de horas")
leia (hora)

//processamento

resultado <- (min/60)+hora

//saída
escreval("o valor é", resultado)
 
fimalgoritmo
