algoritmo "semnome"
// Função :
// Autor :
// Data : 23/05/2021
// Seção de Declarações 
var
num: inteiro

inicio
//entrada

escreval("vamos ver se seu número é considerado par ou impar")
escreval("digite seu número:")
leia(num)

//processamento
se(num mod 2) = 1 entao
escreval("seu número é IMPAR")
fimse

se(num mod 2) = 0 entao
escreval("seu número é PAR")
fimse


fimalgoritmo
